# Generated by Django 3.2.18 on 2023-05-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dining',
            old_name='address_city',
            new_name='address_address',
        ),
        migrations.RenameField(
            model_name='dining',
            old_name='address_dong',
            new_name='address_extra',
        ),
        migrations.RenameField(
            model_name='dining',
            old_name='address_mc_do',
            new_name='address_postcode',
        ),
    ]
