# Generated by Django 3.2.18 on 2023-04-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining',
            name='address_detail',
            field=models.CharField(default=793, max_length=20),
            preserve_default=False,
        ),
    ]
