# Generated by Django 4.2 on 2023-04-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinings', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dinings.dining'),
        ),
    ]
