# Generated by Django 3.2.18 on 2023-05-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinings', '0004_auto_20230428_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(verbose_name='평점'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_kind',
            field=models.FloatField(verbose_name='서비스'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_price',
            field=models.FloatField(verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_taste',
            field=models.FloatField(verbose_name='맛'),
        ),
    ]
