# Generated by Django 3.2.18 on 2023-05-02 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinings', '0005_auto_20230502_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pricetaggeditem',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='pricetaggeditem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='dining',
            name='menu_tags',
        ),
        migrations.RemoveField(
            model_name='dining',
            name='price_tags',
        ),
        migrations.DeleteModel(
            name='MenuTaggedItem',
        ),
        migrations.DeleteModel(
            name='PriceTaggedItem',
        ),
        migrations.AddField(
            model_name='menu',
            name='dining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinings.dining'),
        ),
    ]
